### ISSUE TITLE
Newly created notebook is not indexed

### ISSUE THREAD

**Issue by dleen** [jupyter-server/jupyter_server_fileid#66]
## Description

When I create a new notebook the `save` method is triggered but the notebook is not indexed.

## Reproduce

1. Using `--FileIdExtension.file_id_manager_class=jupyter_server_fileid.manager.LocalFileIdManager`
2. Create a new notebook `Untitled.ipynb`
3. Open the sqlite DB: `sqlite3 /Users/dleen/Library/Jupyter/file_id_manager.db`
4. `SELECT * FROM Files where path like '%.ipynb%';`
5. No results are returned
6. Rename the file: `foo.ipynb`
7. Run the same query, the file is now indexed: `a74e32af-dad7-462d-b299-a0a031f834e1|/Users/dleen/code/catalog/foo.ipynb|93704796|1681152929593818880|1681153012072852876|0`.

## Expected behavior

The initial file `Untitled.ipynb` is indexed.

I added log statements in the `save` method and verified that it is indeed being called. But from reading the code if the file doesn't already exist in the index then the method returns early.

## Discussion

I can't tell if this behavior is expected. That the indexing only happens when a rename happens? 

What is the primary way that a file is supposed to get indexed?

**Comment by dlqqq** [comment]
@dleen Yes, this is intentional for performance reasons. The performance of File ID manager scales roughly logarithmically to the number of files that are indexed, hence we don't want to index a file unless it's necessary. To index a file, you must do it imperatively via the `index()` method.

I'm closing this issue as it's a deliberate feature, but I'm still happy to keep discussing this with you of course.

**Comment by dleen** [comment]
I might be misunderstanding but if it scales logarithmically with the number of files isn't this a very good behavior to have? The cost of additional files is minuscule e.g. 
![log](https://user-images.githubusercontent.com/1297964/231251477-fa9e45a1-b409-4397-af2f-47994ca85fb5.png)

Or do you mean something else?

I do find this behavior a bit confusing as a developer. The rename operation is treated specially. One of the main features of this extension is tracking files across moves and renames, but since the file isn't originally indexed it's a bit strange? I came across this as I was trying to demo creating a file and showing that it keeps the same id across moves.

When testing the extension I had cloned the repository and launched Jupyter from the root of the repo. When I check the index there are 84 indexed files already:
```
sqlite> SELECT COUNT(*) FROM Files;
84
```
the majority of which are git objects:
```
2ec74892-859f-4e10-b719-1b66af038cda|/Users/dleen/code/catalog/jupyter_server_fileid/.git/objects/79|92705687|1680886215374136064|1680886215374911236|1
eeea691b-c207-4b48-a306-9eda4d3b1b60|/Users/dleen/code/catalog/jupyter_server_fileid/.git/objects/2d|92537237|1680830626630919680|1680830626631756103|1
9c2176c6-c69e-4a18-ab05-965120ea75da|/Users/dleen/code/catalog/jupyter_server_fileid/.git/objects/83|92705694|1680886215377887232|1680886215378618165|1
```

If I used this in production in users volumes this would mean indexing a ton of files when the server launches (of the order 1000s). So it seems strange to exclude the ones that are created by users which are going to be in the minority by a large factor. Lets say 10 notebooks created per day for an average user?

Maybe this is another thing that could be configurable? Let users opt in to indexing newly created files? And maybe some exclude options to ignore the `.git` folder?

**Comment by dleen** [comment]
cc @dlqqq

**Comment by dlqqq** [comment]
@dleen We do indeed do **some** auto-indexing, as you've observed. We recursively index all of the directories under the project root, and when a new file is created/deleted in a directory, we can detect it because the `mtime` (modified time) value will change. Thus, we can iterate through all of the directories we previously indexed, compare the `mtime` values, and if they differ, we know that **something** changed in that directory. This is essentially the magic behind `_sync_all()` and why LocalFIM works. 😁 

You can tell that those Git paths are directories, because the value of the `is_dir` (last column) is `1`.

> I do find this behavior a bit confusing as a developer. The rename operation is treated specially. One of the main features of this extension is tracking files across moves and renames, but since the file isn't originally indexed it's a bit strange?

Yeah, that's a great callout. To be honest, this part of the code rarely breaks so I rarely examine it 😂. This looks like some legacy behavior that was introduced in the initial commit: https://github.com/jupyter-server/jupyter_server_fileid/commit/24c6b1c9629047e5a9cd6d07a7efd721ca41d2ef

I agree we should be consistent here; `move()` shouldn't index by default if none of the other public methods do (besides `index()` obviously).

> Maybe this is another thing that could be configurable? Let users opt in to indexing newly created files?

I don't see a reason for why you want to index on save. You don't need to index files preemptively, you can just do it lazily whenever you need the ID. The method `FileIdManager#index()` is idempotent; it will not crash if you give it a file that was already indexed. 

If you can provide me a clear motivation for why this configurability is necessary for your use-case, then I'd be happy to add this to Jupyter File ID.

>  And maybe some exclude options to ignore the .git folder?

I'm very open to this idea.
